language: node_js
node_js:
  - "12.18.2"
sudo: false
before_install:
  - npm install -g codecov
cache:
  yarn: true
env:
  matrix:
  - TEST_SUITE=audit
  - TEST_SUITE=cql4browsers
  - TEST_SUITE=units
script:
  - 'if [ ${TEST_SUITE} = "audit" ]; then
      yarn audit;
    elif [ ${TEST_SUITE} = "cql4browsers" ]; then
      ./bin/validate_cql4browsers.sh;
    else
      ./bin/check_for_nonassertive_tests.sh &&
      yarn test:nyc &&
      codecov;
    fi'
