language: node_js
node_js:
  - "8.9.4"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
before_script:
  - npm install -g coffeelint
  - npm install -g codecov
  - ./bin/validate_cql4browsers.sh
  - ./bin/check_for_nonassertive_tests.sh
  - yarn audit
script:
  - NODE_ENV=test ./node_modules/.bin/nyc --reporter=text-lcov ./node_modules/.bin/mocha --compilers coffee:coffeescript/register --require coffeescript --recursive --colors > coverage.lcov
  - codecov
